- name: Bootstrap development environment
  hosts: localhost
 
  tasks:
  - name: Install packages with apt
    become: yes
    ansible.builtin.apt:
      name:
        - git
        - tmux
      state: present
    when: ansible_distribution == "Ubuntu"
 
  tasks:
  - name: Install packages with brew
    community.general.homebrew:
      name:
        - fish
        - fzf
        - git
        - lazygit
        - neovim
        - nnn
        - rg
        - tmux
        - wezterm
      state: present
    when: ansible_distribution == "MacOSX"
