- name: Bootstrap development environment
  hosts: localhost
 
  tasks:
  - name: Install packages with apt
    become: yes
    ansible.builtin.apt:
      name:
        - git
        - stow
        - tmux
      state: present
    when: ansible_distribution == "Ubuntu"
 
  tasks:
  - name: Install packages with brew
    community.general.homebrew:
      name:
        - docker
        - fish
        - fzf
        - git
        - lazygit
        - neovim
        - n
        - node
        - nnn
        - rg
        - rustup
        - spaceship
        - stow
        - terraform
        - tmux
        - wezterm
        - yarn
      state: present
    when: ansible_distribution == "MacOSX"
